# Generated by Django 3.0.6 on 2020-05-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=999)),
                ('price', models.IntegerField()),
                ('display', models.BooleanField()),
                ('leftInStock', models.IntegerField()),
                ('image', models.CharField(max_length=999)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Manufacturer')),
            ],
        ),
    ]
