# Generated by Django 3.0.6 on 2020-05-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20200513_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
