# Generated by Django 3.0.6 on 2020-05-13 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_delete_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2020, 5, 13, 21, 56, 55, 389191)),
        ),
    ]
