# Generated by Django 3.0.6 on 2020-05-15 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_product_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateAdded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
