# Generated by Django 3.0.6 on 2020-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='dateOfView',
            field=models.DateField(),
        ),
    ]
