# Generated by Django 3.0.6 on 2020-05-14 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
