# Generated by Django 3.0.6 on 2020-05-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
